name: 'Tests'

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    tests:
        name: 'Tests'
        strategy:
          matrix:
            include:
              - php: '8.1.0'
                librdkafka: 'v1.8.2'
                memcheck: '1'
              - php: '8.1.0'
                librdkafka: 'v1.8.2'
              - php: '8.0.12'
                librdkafka: 'v1.8.2'
              - php: '7.4.25'
                librdkafka: 'v1.8.2'
              - php: '8.1.0'
                librdkafka: 'v1.7.0'
              - php: '8.0.12'
                librdkafka: 'v1.7.0'
              - php: '7.4.25'
                librdkafka: 'v1.7.0'
              - php: '8.1.0'
                librdkafka: 'v1.6.1'
              - php: '8.0.12'
                librdkafka: 'v1.6.1'
              - php: '7.4.25'
                librdkafka: 'v1.6.1'
              - php: '8.1.0'
                librdkafka: 'master'
                experimental: true
              - php: '8.0.12'
                librdkafka: 'master'
                experimental: true
              - php: '7.4.25'
                librdkafka: 'master'
                experimental: true

        runs-on: 'ubuntu-18.04'
        continue-on-error: ${{ !!matrix.experimental }}
        env:
            PHP_VERSION: ${{ matrix.php }}
            LIBRDKAFKA_VERSION: ${{ matrix.librdkafka }}
            MEMORY_CHECK: ${{ matrix.memcheck }}
            TEST_KAFKA_BROKERS: kafka:9092
            TEST_KAFKA_BROKER_VERSION: 2.6
        steps:
            - name: 'Check out repository'
              uses: 'actions/checkout@v2'
              with:
                  path: 'php-simple-kafka-client'

            - uses: actions/cache@v2
              with:
                  path: ~/build-cache/php
                  key: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.memcheck }}

            - uses: actions/cache@v2
              with:
                  path: ~/build-cache/librdkafka
                  key: ${{ runner.os }}-${{ matrix.librdkafka }}

            - name: 'Build librdkafka'
              run: './php-simple-kafka-client/.github/workflows/test/build-librdkafka.sh'

            - name: 'Build PHP'
              run: './php-simple-kafka-client/.github/workflows/test/build-php.sh'

            - name: 'Build php-simple-kafka-client'
              run: './php-simple-kafka-client/.github/workflows/test/build-php-simple-kafka-client.sh'

            - name: 'Start Kafka'
              run: './php-simple-kafka-client/.github/workflows/test/start-kafka.sh'

            - name: 'Run tests'
              run: './php-simple-kafka-client/.github/workflows/test/tests.sh'
